### ISSUE TITLE
Support Play 1.5 (Hibernate 5.2)

### ISSUE THREAD

**Issue by tazmaniax** [tazmaniax/play--database#1]

**Comment by tazmaniax** [comment]
The play.db.DB.datasources static field is not being initialised by play.db.DBPlugin.onApplicationStart() in time before it is being referenced by play.modules.db.Exporter.properties() on line [164](https://github.com/tazmaniax/play--database/blob/play-db%231-Support_Play_1.5/src/play/modules/db/Exporter.java#L164). This is unexpected as Play.init(...) is being called before and that should initialise the plugins first, no?

On a side note I had to copy db.jpa.JPAPlugin methods properties(String dbName, Configuration dbConfig) and entityClasses(String dbName) as access is restricted to db.jpa.JPAPlugin. I'm wondering if those methods can be made public?

```
chris$ play-15x db:export
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.5.x-1.4.4-64-g40f51354, https://www.playframework.com
~
~ Generating ddl database file
~ 
~ using java version "1.8.0_121"
objc[17269]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x10c5b34c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10c6c64e0). One of the two will be used. Which one is undefined.
Listening for transport dt_socket at address: 8000
00:40:54,091 [main] INFO  ~ Starting /Users/chris/git/PTAsocial
:: loading settings :: url = jar:file:/usr/local/play-1.5.x-1.4.4-64-g40f51354/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
00:40:54,451 [main] INFO  ~ Module crud is available (/usr/local/play-1.5.x-1.4.4-64-g40f51354/modules/crud)
00:40:54,451 [main] INFO  ~ Module fastergt is available (/Users/chris/git/PTAsocial/modules/fastergt-1.9.2)
00:40:54,451 [main] INFO  ~ Module db is available (/Users/chris/git/PTAsocial/modules/db-1.2)
00:40:54,451 [main] INFO  ~ Module accesslog is available (/Users/chris/git/PTAsocial/modules/accesslog-1.2)
00:40:54,452 [main] INFO  ~ Module deadbolt is available (/Users/chris/git/PTAsocial/modules/deadbolt-1.5.4)
00:40:54,452 [main] INFO  ~ Module coffee is available (/Users/chris/git/PTAsocial/modules/coffee-1.0)
00:40:54,452 [main] INFO  ~ Module securesocial is available (/Users/chris/git/PTAsocial/modules/securesocial-0.2.7)
00:40:56,277 [main] INFO  ~ Loaded image cleaner plugin
00:40:56,289 [main] WARN  ~ You're running Play! in DEV mode
Exception in thread "main" java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at play.modules.db.Exporter.properties(Exporter.java:164)
	at play.modules.db.Exporter.main(Exporter.java:107)
```

**Comment by asolntsev** [comment]
@tazmaniax What exactly are you proposing? Do you suggest to make public couple of methods in `JPAPlugin`? Probably. But probably it's better to fix `DBPlugin` to initialize static field `play.db.DB.datasources` during `Play.init()`?

**Comment by tazmaniax** [comment]
@asolntsev so I did a bit more digging in the Play source and found that `play.Play.init(File, String)` does not call `Play.start()` in [dev mode](https://github.com/playframework/play1/blob/master/framework/src/play/Play.java#L325), which means `play.db.DBPlugin.onApplicationStart()` is not called and therefore `play.db.DB.datasources` is not initialised - `onApplicationStart()` must be called from a different part of the code in dev mode but I couldn't find it so instead I decided to borrow some code from `play.db.Evolutions.main(String[])`, which has a similar scope, and use that replace the call to 'play.Play.init(File, String)`...
```
        /** Start the DB plugin **/
        Play.guessFrameworkPath();
        Play.readConfiguration();
        Play.classes = new ApplicationClasses();
        Play.classloader = new ApplicationClassloader();

        Play.loadModules(VirtualFile.open(Play.applicationPath));

        Logger.init();
        Logger.setUp("ERROR");
        new DBPlugin().onApplicationStart();
```
So that change gets me a bit further and now I have a Hibernate exception that looks like a class loading issue...
```
➜  PTAsocial git:(github#401-play_1_5_support) ✗ play-15x db:export . --create --output=create.sql --%dbgen
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.5.x-1.4.4-64-g40f51354, https://www.playframework.com
~ framework ID is dbgen
~
~ Generating ddl database file
~ 
~ using java version "1.8.0_131"
objc[5631]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x108c574c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x108d324e0). One of the two will be used. Which one is undefined.
Listening for transport dt_socket at address: 8000
Aug 20, 2017 10:35:46 PM play.Logger warn
WARNING: Cannot replace USE_JAVASCRIPT_SOURCE in configuration (useJavaScriptSource=${USE_JAVASCRIPT_SOURCE})
Aug 20, 2017 10:35:46 PM play.Logger warn
WARNING: Cannot replace GOOGLE_SERVER_API_KEY in configuration (google.server.api.key=${GOOGLE_SERVER_API_KEY})
Aug 20, 2017 10:35:46 PM play.Logger warn
WARNING: Cannot replace GOOGLE_BROWSER_API_KEY in configuration (google.browser.api.key=${GOOGLE_BROWSER_API_KEY})
Aug 20, 2017 10:35:46 PM play.Logger warn
WARNING: Cannot replace PROXIMO_URL in configuration (proxy.url=${PROXIMO_URL})
Aug 20, 2017 10:35:46 PM play.Logger warn
WARNING: Cannot replace FRESHDESK_SECRET_KEY in configuration (freshdesk.secretKey=${FRESHDESK_SECRET_KEY})
:: loading settings :: url = jar:file:/usr/local/play-1.5.x-1.4.4-64-g40f51354/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Aug 20, 2017 10:35:51 PM play.Logger info
INFO: Module crud is available (/usr/local/play-1.5.x-1.4.4-64-g40f51354/modules/crud)
Aug 20, 2017 10:35:51 PM play.Logger info
INFO: Module fastergt is available (/Users/chris/git/PTAsocial/modules/fastergt-1.9.4)
Aug 20, 2017 10:35:51 PM play.Logger info
INFO: Module db is available (/Users/chris/git/PTAsocial/modules/db-1.3)
Aug 20, 2017 10:35:51 PM play.Logger info
INFO: Module accesslog is available (/Users/chris/git/PTAsocial/modules/accesslog-1.2)
Aug 20, 2017 10:35:51 PM play.Logger info
INFO: Module deadbolt is available (/Users/chris/git/PTAsocial/modules/deadbolt-1.5.4)
Aug 20, 2017 10:35:51 PM play.Logger info
INFO: Module coffee is available (/Users/chris/git/PTAsocial/modules/coffee-1.0)
Aug 20, 2017 10:35:51 PM play.Logger info
INFO: Module securesocial is available (/Users/chris/git/PTAsocial/modules/securesocial-0.2.7)
22:35:58,655 [main] WARN  ~ HHH000342: Could not obtain connection to query metadata : Unable to resolve name [utils.hibernate.CustomMySQL5InnoDBDialect] as strategy [org.hibernate.dialect.Dialect]
Exception in thread "main" org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:271)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:233)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:242)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:83)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:418)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:87)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:179)
	at play.modules.db.Exporter.main(Exporter.java:150)
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [utils.hibernate.CustomMySQL5InnoDBDialect] as strategy [org.hibernate.dialect.Dialect]
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:126)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:194)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:152)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:139)
	at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:133)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.constructDialect(DialectFactoryImpl.java:74)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:51)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:259)
	... 13 more
```

**Comment by tazmaniax** [comment]
The Hibernate [ClassLoaderServiceImpl](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/boot/registry/classloading/internal/ClassLoaderServiceImpl.java#L134) should be picking up the thread context class loader [that is being set](https://github.com/tazmaniax/play--database/blob/play-db%231-Support_Play_1.5/src/play/modules/db/Exporter.java#L112) and therefore Hibernate should be able to find the applications classes and specifically the required custom MySQL dialect `utils.hibernate.CustomMySQL5InnoDBDialect`, but it's not. Maybe the `Play.classloader` is not being initialised correctly.

**Comment by tazmaniax** [comment]
Class loading issues resolved - it was because it hadn't been setup properly - and it all seems to be working now. The only non ideal is the copying of a couple of methods from JPAPlugin to setup config and retrieve entity classes. At some point maybe those methods could be made public on JPAPlugin.

**Comment by asolntsev** [comment]
@tazmaniax I agree, it would be better if `DBPlugin` initialized data sources during `Play.init()`, not after start. Let's implement it!
